run:
	go run .

build:
	go build .

generate-assets:
	echo "Generate all static assets..."
	go-bindata-assetfs -o templates/asset.go -pkg assetHTML templates/...
	go-bindata-assetfs -o assets/css/asset.go -pkg assetCSS assets/css/...
	go-bindata-assetfs -o assets/fonts/asset.go -pkg assetFonts assets/fonts/...
	go-bindata-assetfs -o assets/img/asset.go -pkg assetIMG assets/img/...
	go-bindata-assetfs -o assets/js/asset.go -pkg assetJS assets/js/...
	go-bindata-assetfs -o assets/scss/asset.go -pkg assetSCSS assets/scss/...
	go-bindata-assetfs -o assets/vendor/asset.go -pkg assetVendor assets/vendor/...